# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.actions_id_action_board.get import GetBoardByIdAction
from trello_python_sdk.paths.actions_id_action_board_field.get import GetBoardByIdActionByField
from trello_python_sdk.paths.actions_id_action.get import GetById
from trello_python_sdk.paths.actions_id_action_field.get import GetByIdActionField
from trello_python_sdk.paths.actions_id_action_card.get import GetCardByIdAction
from trello_python_sdk.paths.actions_id_action_card_field.get import GetCardByIdActionByField
from trello_python_sdk.paths.actions_id_action_display.get import GetDisplayByIdAction
from trello_python_sdk.paths.actions_id_action_entities.get import GetEntitiesByIdAction
from trello_python_sdk.paths.actions_id_action_list.get import GetListByIdAction
from trello_python_sdk.paths.actions_id_action_list_field.get import GetListByIdActionByField
from trello_python_sdk.paths.actions_id_action_member_field.get import GetMemberByField
from trello_python_sdk.paths.actions_id_action_member.get import GetMemberByIdAction
from trello_python_sdk.paths.actions_id_action_member_creator_field.get import GetMemberByIdActionByField
from trello_python_sdk.paths.actions_id_action_member_creator.get import GetMemberCreatorByIdAction
from trello_python_sdk.paths.actions_id_action_organization_field.get import GetOrgByIdActionByField
from trello_python_sdk.paths.actions_id_action_organization.get import GetOrganizationByIdAction
from trello_python_sdk.paths.actions_id_action.delete import RemoveByIdAction
from trello_python_sdk.paths.actions_id_action.put import UpdateByIdAction
from trello_python_sdk.paths.actions_id_action_text.put import UpdateTextByIdAction
from trello_python_sdk.apis.tags.action_api_raw import ActionApiRaw


class ActionApi(
    GetBoardByIdAction,
    GetBoardByIdActionByField,
    GetById,
    GetByIdActionField,
    GetCardByIdAction,
    GetCardByIdActionByField,
    GetDisplayByIdAction,
    GetEntitiesByIdAction,
    GetListByIdAction,
    GetListByIdActionByField,
    GetMemberByField,
    GetMemberByIdAction,
    GetMemberByIdActionByField,
    GetMemberCreatorByIdAction,
    GetOrgByIdActionByField,
    GetOrganizationByIdAction,
    RemoveByIdAction,
    UpdateByIdAction,
    UpdateTextByIdAction,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ActionApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ActionApiRaw(api_client)
