# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.batch.get import GetData
from trello_python_sdk.apis.tags.batch_api_raw import BatchApiRaw


class BatchApi(
    GetData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BatchApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BatchApiRaw(api_client)
