# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.checklists_id_checklist_check_items.post import AddCheckItemsByIdChecklistRaw
from trello_python_sdk.paths.checklists.post import CreateRaw
from trello_python_sdk.paths.checklists_id_checklist_board.get import GetBoardByIdChecklistRaw
from trello_python_sdk.paths.checklists_id_checklist_board_field.get import GetBoardByIdChecklistByFieldRaw
from trello_python_sdk.paths.checklists_id_checklist.get import GetByIdRaw
from trello_python_sdk.paths.checklists_id_checklist_field.get import GetByIdFieldRaw
from trello_python_sdk.paths.checklists_id_checklist_cards_filter.get import GetCardsByFilterRaw
from trello_python_sdk.paths.checklists_id_checklist_check_items.get import GetCheckItemsByIdChecklistRaw
from trello_python_sdk.paths.checklists_id_checklist_check_items_id_check_item.get import GetCheckItemsByIdChecklistByIdCheckItemRaw
from trello_python_sdk.paths.checklists_id_checklist_cards.get import ListCardsByIdChecklistRaw
from trello_python_sdk.paths.checklists_id_checklist.delete import RemoveByIdRaw
from trello_python_sdk.paths.checklists_id_checklist_check_items_id_check_item.delete import RemoveByIdCheckItemRaw
from trello_python_sdk.paths.checklists_id_checklist.put import UpdateByIdChecklistRaw
from trello_python_sdk.paths.checklists_id_checklist_id_card.put import UpdateIdCardByIdChecklistRaw
from trello_python_sdk.paths.checklists_id_checklist_name.put import UpdateNameByIdChecklistRaw
from trello_python_sdk.paths.checklists_id_checklist_pos.put import UpdatePosByIdChecklistRaw


class ChecklistApiRaw(
    AddCheckItemsByIdChecklistRaw,
    CreateRaw,
    GetBoardByIdChecklistRaw,
    GetBoardByIdChecklistByFieldRaw,
    GetByIdRaw,
    GetByIdFieldRaw,
    GetCardsByFilterRaw,
    GetCheckItemsByIdChecklistRaw,
    GetCheckItemsByIdChecklistByIdCheckItemRaw,
    ListCardsByIdChecklistRaw,
    RemoveByIdRaw,
    RemoveByIdCheckItemRaw,
    UpdateByIdChecklistRaw,
    UpdateIdCardByIdChecklistRaw,
    UpdateNameByIdChecklistRaw,
    UpdatePosByIdChecklistRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
