# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.labels.post import CreateLabelsRaw
from trello_python_sdk.paths.labels_id_label_board.get import GetBoardByIdLabelRaw
from trello_python_sdk.paths.labels_id_label_board_field.get import GetBoardByIdLabelByFieldRaw
from trello_python_sdk.paths.labels_id_label.get import GetByIdLabelRaw
from trello_python_sdk.paths.labels_id_label.delete import RemoveByIdLabelRaw
from trello_python_sdk.paths.labels_id_label.put import UpdateByIdLabelRaw
from trello_python_sdk.paths.labels_id_label_color.put import UpdateColorByIdLabelRaw
from trello_python_sdk.paths.labels_id_label_name.put import UpdateNameByIdLabelRaw


class LabelApiRaw(
    CreateLabelsRaw,
    GetBoardByIdLabelRaw,
    GetBoardByIdLabelByFieldRaw,
    GetByIdLabelRaw,
    RemoveByIdLabelRaw,
    UpdateByIdLabelRaw,
    UpdateColorByIdLabelRaw,
    UpdateNameByIdLabelRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
