# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.lists_id_list_archive_all_cards.post import ArchiveAllCardsByIdListRaw
from trello_python_sdk.paths.lists_id_list_cards.post import CreateCardsByIdListRaw
from trello_python_sdk.paths.lists.post import CreateListRaw
from trello_python_sdk.paths.lists_id_list_actions.get import GetActionsByIdListRaw
from trello_python_sdk.paths.lists_id_list_board_field.get import GetBoardByIdListByFieldRaw
from trello_python_sdk.paths.lists_id_list.get import GetByIdListRaw
from trello_python_sdk.paths.lists_id_list_field.get import GetByIdListByFieldRaw
from trello_python_sdk.paths.lists_id_list_cards_filter.get import GetCardsByFilterRaw
from trello_python_sdk.paths.lists_id_list_cards.get import GetCardsByIdListRaw
from trello_python_sdk.paths.lists_id_list_board.get import IdBoardGetRaw
from trello_python_sdk.paths.lists_id_list_move_all_cards.post import MoveAllCardsByIdListRaw
from trello_python_sdk.paths.lists_id_list.put import UpdateByIdListRaw
from trello_python_sdk.paths.lists_id_list_closed.put import UpdateClosedByIdListRaw
from trello_python_sdk.paths.lists_id_list_id_board.put import UpdateIdBoardByIdListRaw
from trello_python_sdk.paths.lists_id_list_name.put import UpdateNameByIdListRaw
from trello_python_sdk.paths.lists_id_list_pos.put import UpdatePosByIdListRaw
from trello_python_sdk.paths.lists_id_list_subscribed.put import UpdateSubscribedByIdListRaw


class ModelListApiRaw(
    ArchiveAllCardsByIdListRaw,
    CreateCardsByIdListRaw,
    CreateListRaw,
    GetActionsByIdListRaw,
    GetBoardByIdListByFieldRaw,
    GetByIdListRaw,
    GetByIdListByFieldRaw,
    GetCardsByFilterRaw,
    GetCardsByIdListRaw,
    IdBoardGetRaw,
    MoveAllCardsByIdListRaw,
    UpdateByIdListRaw,
    UpdateClosedByIdListRaw,
    UpdateIdBoardByIdListRaw,
    UpdateNameByIdListRaw,
    UpdatePosByIdListRaw,
    UpdateSubscribedByIdListRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
