# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.notifications_id_notification_board_field.get import GetBoardByField
from trello_python_sdk.paths.notifications_id_notification_board.get import GetBoardById
from trello_python_sdk.paths.notifications_id_notification.get import GetById
from trello_python_sdk.paths.notifications_id_notification_field.get import GetByIdField
from trello_python_sdk.paths.notifications_id_notification_card.get import GetCardById
from trello_python_sdk.paths.notifications_id_notification_card_field.get import GetCardByIdNotificationByField
from trello_python_sdk.paths.notifications_id_notification_display.get import GetDisplayByIdNotification
from trello_python_sdk.paths.notifications_id_notification_entities.get import GetEntitiesByIdNotification
from trello_python_sdk.paths.notifications_id_notification_list.get import GetListByIdNotification
from trello_python_sdk.paths.notifications_id_notification_list_field.get import GetListByIdNotificationByField
from trello_python_sdk.paths.notifications_id_notification_member_field.get import GetMemberByIdField
from trello_python_sdk.paths.notifications_id_notification_member_creator_field.get import GetMemberByIdNotificationByField
from trello_python_sdk.paths.notifications_id_notification_member.get import GetMemberByNotification
from trello_python_sdk.paths.notifications_id_notification_member_creator.get import GetMemberCreatorById
from trello_python_sdk.paths.notifications_id_notification_organization.get import GetOrganizationByIdNotification
from trello_python_sdk.paths.notifications_id_notification_organization_field.get import GetOrganizationByIdNotificationByField
from trello_python_sdk.paths.notifications_all_read.post import MarkAllAsRead
from trello_python_sdk.paths.notifications_id_notification.put import UpdateByIdNotification
from trello_python_sdk.paths.notifications_id_notification_unread.put import UpdateUnreadByIdNotification
from trello_python_sdk.apis.tags.notification_api_raw import NotificationApiRaw


class NotificationApi(
    GetBoardByField,
    GetBoardById,
    GetById,
    GetByIdField,
    GetCardById,
    GetCardByIdNotificationByField,
    GetDisplayByIdNotification,
    GetEntitiesByIdNotification,
    GetListByIdNotification,
    GetListByIdNotificationByField,
    GetMemberByIdField,
    GetMemberByIdNotificationByField,
    GetMemberByNotification,
    GetMemberCreatorById,
    GetOrganizationByIdNotification,
    GetOrganizationByIdNotificationByField,
    MarkAllAsRead,
    UpdateByIdNotification,
    UpdateUnreadByIdNotification,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: NotificationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = NotificationApiRaw(api_client)
