# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.notifications_id_notification_board_field.get import GetBoardByFieldRaw
from trello_python_sdk.paths.notifications_id_notification_board.get import GetBoardByIdRaw
from trello_python_sdk.paths.notifications_id_notification.get import GetByIdRaw
from trello_python_sdk.paths.notifications_id_notification_field.get import GetByIdFieldRaw
from trello_python_sdk.paths.notifications_id_notification_card.get import GetCardByIdRaw
from trello_python_sdk.paths.notifications_id_notification_card_field.get import GetCardByIdNotificationByFieldRaw
from trello_python_sdk.paths.notifications_id_notification_display.get import GetDisplayByIdNotificationRaw
from trello_python_sdk.paths.notifications_id_notification_entities.get import GetEntitiesByIdNotificationRaw
from trello_python_sdk.paths.notifications_id_notification_list.get import GetListByIdNotificationRaw
from trello_python_sdk.paths.notifications_id_notification_list_field.get import GetListByIdNotificationByFieldRaw
from trello_python_sdk.paths.notifications_id_notification_member_field.get import GetMemberByIdFieldRaw
from trello_python_sdk.paths.notifications_id_notification_member_creator_field.get import GetMemberByIdNotificationByFieldRaw
from trello_python_sdk.paths.notifications_id_notification_member.get import GetMemberByNotificationRaw
from trello_python_sdk.paths.notifications_id_notification_member_creator.get import GetMemberCreatorByIdRaw
from trello_python_sdk.paths.notifications_id_notification_organization.get import GetOrganizationByIdNotificationRaw
from trello_python_sdk.paths.notifications_id_notification_organization_field.get import GetOrganizationByIdNotificationByFieldRaw
from trello_python_sdk.paths.notifications_all_read.post import MarkAllAsReadRaw
from trello_python_sdk.paths.notifications_id_notification.put import UpdateByIdNotificationRaw
from trello_python_sdk.paths.notifications_id_notification_unread.put import UpdateUnreadByIdNotificationRaw


class NotificationApiRaw(
    GetBoardByFieldRaw,
    GetBoardByIdRaw,
    GetByIdRaw,
    GetByIdFieldRaw,
    GetCardByIdRaw,
    GetCardByIdNotificationByFieldRaw,
    GetDisplayByIdNotificationRaw,
    GetEntitiesByIdNotificationRaw,
    GetListByIdNotificationRaw,
    GetListByIdNotificationByFieldRaw,
    GetMemberByIdFieldRaw,
    GetMemberByIdNotificationByFieldRaw,
    GetMemberByNotificationRaw,
    GetMemberCreatorByIdRaw,
    GetOrganizationByIdNotificationRaw,
    GetOrganizationByIdNotificationByFieldRaw,
    MarkAllAsReadRaw,
    UpdateByIdNotificationRaw,
    UpdateUnreadByIdNotificationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
