# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.search_members.get import FindMembers
from trello_python_sdk.paths.search.get import GetResults
from trello_python_sdk.apis.tags.search_api_raw import SearchApiRaw


class SearchApi(
    FindMembers,
    GetResults,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SearchApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SearchApiRaw(api_client)
