# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.sessions.post import CreateAndUpdate
from trello_python_sdk.paths.sessions_socket.get import GetSocketSessions
from trello_python_sdk.paths.sessions_id_session.put import UpdateStatusByIdSession
from trello_python_sdk.paths.sessions_id_session_status.put import UpdateStatusByIdSession0
from trello_python_sdk.apis.tags.session_api_raw import SessionApiRaw


class SessionApi(
    CreateAndUpdate,
    GetSocketSessions,
    UpdateStatusByIdSession,
    UpdateStatusByIdSession0,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SessionApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SessionApiRaw(api_client)
