# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.sessions.post import CreateAndUpdateRaw
from trello_python_sdk.paths.sessions_socket.get import GetSocketSessionsRaw
from trello_python_sdk.paths.sessions_id_session.put import UpdateStatusByIdSessionRaw
from trello_python_sdk.paths.sessions_id_session_status.put import UpdateStatusByIdSession0Raw


class SessionApiRaw(
    CreateAndUpdateRaw,
    GetSocketSessionsRaw,
    UpdateStatusByIdSessionRaw,
    UpdateStatusByIdSession0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
