# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.tokens_token.delete import DeleteByToken
from trello_python_sdk.paths.tokens_token.get import GetByToken
from trello_python_sdk.paths.tokens_token_field.get import GetByTokenByField
from trello_python_sdk.paths.tokens_token_member_field.get import GetMemberByField
from trello_python_sdk.paths.tokens_token_member.get import GetMemberByToken
from trello_python_sdk.paths.tokens_token_webhooks_id_webhook.get import GetWebhookById
from trello_python_sdk.paths.tokens_token_webhooks.get import GetWebhooks
from trello_python_sdk.paths.tokens_token_webhooks.post import RegisterWebhook
from trello_python_sdk.paths.tokens_token_webhooks_id_webhook.delete import RemoveByTokenByIdWebhook
from trello_python_sdk.paths.tokens_token_webhooks.put import UpdateWebhooksByToken
from trello_python_sdk.apis.tags.token_api_raw import TokenApiRaw


class TokenApi(
    DeleteByToken,
    GetByToken,
    GetByTokenByField,
    GetMemberByField,
    GetMemberByToken,
    GetWebhookById,
    GetWebhooks,
    RegisterWebhook,
    RemoveByTokenByIdWebhook,
    UpdateWebhooksByToken,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TokenApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TokenApiRaw(api_client)
