# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.webhooks_id_webhook.get import GetById
from trello_python_sdk.paths.webhooks_id_webhook_field.get import GetByIdField
from trello_python_sdk.paths.webhooks_id_webhook.delete import RemoveById
from trello_python_sdk.paths.webhooks.put import Update
from trello_python_sdk.paths.webhooks_id_webhook_active.put import UpdateActiveById
from trello_python_sdk.paths.webhooks_id_webhook.put import UpdateByIdWebhook
from trello_python_sdk.paths.webhooks_id_webhook_callback_url.put import UpdateCallbackUrlById
from trello_python_sdk.paths.webhooks_id_webhook_description.put import UpdateDescriptionByIdWebhook
from trello_python_sdk.paths.webhooks_id_webhook_id_model.put import UpdateModelById
from trello_python_sdk.apis.tags.webhook_api_raw import WebhookApiRaw


class WebhookApi(
    GetById,
    GetByIdField,
    RemoveById,
    Update,
    UpdateActiveById,
    UpdateByIdWebhook,
    UpdateCallbackUrlById,
    UpdateDescriptionByIdWebhook,
    UpdateModelById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WebhookApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WebhookApiRaw(api_client)
