# coding: utf-8

"""
    Trello

    This document describes the REST API of Trello as published by Trello.com.  - <a href='https://trello.com/docs/index.html' target='_blank'>Official Documentation</a>  - <a href='https://trello.com/docs/api' target='_blank'>The HTML pages that were scraped in order to generate this specification.</a>

    The version of the OpenAPI document: 1.0
    Created by: https://trello.com/home
"""

from trello_python_sdk.paths.webhooks_id_webhook.get import GetByIdRaw
from trello_python_sdk.paths.webhooks_id_webhook_field.get import GetByIdFieldRaw
from trello_python_sdk.paths.webhooks_id_webhook.delete import RemoveByIdRaw
from trello_python_sdk.paths.webhooks.put import UpdateRaw
from trello_python_sdk.paths.webhooks_id_webhook_active.put import UpdateActiveByIdRaw
from trello_python_sdk.paths.webhooks_id_webhook.put import UpdateByIdWebhookRaw
from trello_python_sdk.paths.webhooks_id_webhook_callback_url.put import UpdateCallbackUrlByIdRaw
from trello_python_sdk.paths.webhooks_id_webhook_description.put import UpdateDescriptionByIdWebhookRaw
from trello_python_sdk.paths.webhooks_id_webhook_id_model.put import UpdateModelByIdRaw


class WebhookApiRaw(
    GetByIdRaw,
    GetByIdFieldRaw,
    RemoveByIdRaw,
    UpdateRaw,
    UpdateActiveByIdRaw,
    UpdateByIdWebhookRaw,
    UpdateCallbackUrlByIdRaw,
    UpdateDescriptionByIdWebhookRaw,
    UpdateModelByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
